SERVER="https://tap.embarklabs.ai"  # XNAT sever e.g. https://myxnat.org
PROJECT="MYPROJECT"                     # Project where environments are uploaded, e.g MYPROJECT

#Upload a micromamba user environment to XNAT
UPLOAD_ENV=0
LOCAL_ENV_FOLDER="/path/to/micromamba/environment"
REMOTE_ENV_RESOURCE="ENVS"
#Unused for now
#REMOTE_ENV_FOLDER="nsclc-segmentation-codebase-20260317-env"

#Upload user source code to XNAT
UPLOAD_USER_SOURCE=0
LOCAL_USER_SOURCE_FOLDER="/path/to/local/user/source"
REMOTE_USER_SOURCE_RESOURCE="SRC"
#Unused for now
#REMOTE_USER_SOURCE_FOLDER="nsclc-segmentation-codebase-20260317"
